### ISSUE TITLE
WooCommerce One Step Checkout plugin ain't workign

### ISSUE THREAD

**Issue by nickkuijpers** [ThemeFuse/Unyson-Shortcodes-Extension#20]
Hi, 

I've waited for the latest release of the plugin hoping this bug would be solved but the WooCommerce One Page Checkout plugin from WooThemes isn't working yet. 

Please install the plugin on a fresh Wordpress installation an try it with a product. You'll see it directly.

**Comment by moldcraft** [comment]
> hoping **this bug** would be solved

Which bug? Is it mentioned in the changelog of the plugin?

**Comment by nickkuijpers** [comment]
We've had an discussion in a post which i cannot find anymore, 2 weeks ago about the shortcode bug when adding WooCommerce shortcodes which doesn't work.

**Comment by nickkuijpers** [comment]
Hi, is there any progress on this issue?

**Comment by nickkuijpers** [comment]
Hello? Its been 13 days.. I cant get this to work. I'm almost required to use a other plugin...

**Comment by GheorgheP** [comment]
Hi,

Sorry for big delay.

We contacted the guys from WooCommerce to give us access to the Woo Plugins in order to check the compatibility.

**Comment by nickkuijpers** [comment]
Hi! 

Any progress on this? I can send u the files? Its taking really long and i need to deliver the website next week.. :(

Thanks!

**Comment by GheorgheP** [comment]
Hi,

Send them on dev-team@unyson.io

**Comment by nickkuijpers** [comment]
Hi, 

How is it going?

**Comment by GheorgheP** [comment]
Hi,

I investigated the problem and there is a small problem between our page builder and the plugin.

The idea is that the plugin checks every posted/updated page of containing the `woocommerce_one_page_checkout` shortcode: `woocommerce-one-page-checkout.php 1199`
``` php
if ( false !== stripos( $post->post_content, '[woocommerce_one_page_checkout' ) ) {
	self::$add_scripts = true;
	self::$shortcode_page_id = $post->ID;
	break;
}
``` 

But in the `text block` shortcode the text, because it is added as attribute, so the `[` symbol is also encoded, so in the `1199` line, it cannot find the shortcode with `strreplace()`.
THe easiest solution is to edit the line `119` from `woocommerce-one-page-checkout.php`.

We will investigate this, but at the moment I cannot provide other solution.

**Comment by nickkuijpers** [comment]
Awesome! Thanks Gheorghe! Looking into that tomorrow!

**Comment by nickkuijpers** [comment]
Thanks Gheorghe.

Fixed it by renaming the [woocommerce_one... to woocommerce_one...

Not the best solutions but it will work.

Does this affect to other plugins too in the future?

**Comment by GheorgheP** [comment]
I don't think that this will affect the other plugins in future, but we will investigate and solve this too if it would be possible.

**Comment by nickkuijpers** [comment]
Thanks alot :) :+1:
